### ISSUE TITLE
passing getState param to Saga

### ISSUE THREAD

**Issue by yelouafi** [salsita/redux-saga-rxjs#1]
Shouldn't getState passed to the Saga here ?

https://github.com/tomkis1/redux-saga-rxjs/blob/master/src/index.js#L8

**Comment by tomkis** [comment]
this still needs to be decided according to https://github.com/yelouafi/redux-saga/issues/8 because I actually share @slorber 's view.

**Comment by slorber** [comment]
users can get access to state and choose to use it by themselves (or not). Both work anyway

**Comment by tomkis** [comment]
Fixed in https://github.com/tomkis1/redux-saga-rxjs/commit/1bf221da923af36f87f2f29ecbad1d334dfd9ecd
