### ISSUE TITLE
return `next(action)` from middleware

### ISSUE THREAD

**Issue by mxdubois** [salsita/redux-saga-rxjs#3]
Hey. I was just trying out your library and it's awesome! Great that such a simple lib can leverage all the power of rxjs.

I hit one snag, though. Your middleware breaks my `dispatch` pipeline, which currently returns the final dispatched action. I believe middleware should typically `return next(action)` instead of `undefined`. Is there any reason you didn't want to?

This matters for me because I inspect some `meta` info attached by my middleware to trace the completion of async actions but I'm sure I could work around it if you had a reason for returning `undefined`.

**Comment by tomkis** [comment]
Thanks! Will fix that.

**Comment by tomkis** [comment]
Fixed in 0.3.0
