### ISSUE TITLE
unknown type returned

### ISSUE THREAD

**Issue by thorbenandresen** [salsita/redux-saga-rxjs#4]
Hi,

this here works for me

``` js
export const saga = iterable => iterable
  .filter(({ action, state }) => action.type === 'FOO')
  .map(() => ({type: 'BAR'}))
```

this here does not work

``` js
export const saga = iterable => iterable
  .filter(({ action, state }) => action.type === 'FOO')
  .flatMap(() => Observable
    .fromPromise(AsyncStorage.getItem('items'))
    .map(items => ({type: 'BAR', data: items})))
```

![screen shot 2016-03-20 at 8 16 17 pm](https://cloud.githubusercontent.com/assets/8238976/13908500/fd91aa98-eed9-11e5-998b-d3145acd564a.png)

I am still trying to wrap my head around sagas+rx, but based on [this example](https://github.com/salsita/redux-saga-rxjs/blob/master/examples/auth/src/sagas/authSaga.js#L29-L34) it should work, right?

**Comment by tomkis** [comment]
Hello @Thorbenandresen,

Your example does indeed seems correct to me.

``` javascript
export default iterable => iterable
  .filter(({ action, state }) => action.type === 'Boot')
  .flatMap(() => Observable
    .fromPromise(new Promise(res => res()))
    .map(() => ({type: 'BAR', data: []})));
```

Here's my code which WFM.

Maybe you could provide more complete example?

**Comment by thorbenandresen** [comment]
@tomkis1 - thanks, I found my mistake. I was using `import {Observable} from 'rx'` instead of `import {Observable} from 'rxjs'`. (importing from 'rx' works in my thunks where I use Observables, thats why I was misled)  Sorry for that!
